# Form implementation generated from reading ui file 'primary.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PrimaryWindow(object):
    def setupUi(self, PrimaryWindow):
        PrimaryWindow.setObjectName("PrimaryWindow")
        PrimaryWindow.resize(639, 689)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        PrimaryWindow.setFont(font)
        PrimaryWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        PrimaryWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(PrimaryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 310, 621, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.solution_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.solution_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.solution_vertical_layout.setObjectName("solution_vertical_layout")
        self.tab_all = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_all.setFont(font)
        self.tab_all.setIconSize(QtCore.QSize(16, 16))
        self.tab_all.setObjectName("tab_all")
        self.tab_astrometry = QtWidgets.QWidget()
        self.tab_astrometry.setObjectName("tab_astrometry")
        self.tab_all.addTab(self.tab_astrometry, "")
        self.tab_photometry = QtWidgets.QWidget()
        self.tab_photometry.setObjectName("tab_photometry")
        self.tab_all.addTab(self.tab_photometry, "")
        self.tab_propagate = QtWidgets.QWidget()
        self.tab_propagate.setObjectName("tab_propagate")
        self.tab_all.addTab(self.tab_propagate, "")
        self.tab_orbit = QtWidgets.QWidget()
        self.tab_orbit.setObjectName("tab_orbit")
        self.tab_all.addTab(self.tab_orbit, "")
        self.tab_ephemeris = QtWidgets.QWidget()
        self.tab_ephemeris.setObjectName("tab_ephemeris")
        self.tab_all.addTab(self.tab_ephemeris, "")
        self.solution_vertical_layout.addWidget(self.tab_all)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 621, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.image_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.image_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.image_vertical_layout.setObjectName("image_vertical_layout")
        PrimaryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PrimaryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 25))
        self.menubar.setObjectName("menubar")
        PrimaryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PrimaryWindow)
        self.statusbar.setObjectName("statusbar")
        PrimaryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PrimaryWindow)
        self.tab_all.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(PrimaryWindow)

    def retranslateUi(self, PrimaryWindow):
        _translate = QtCore.QCoreApplication.translate
        PrimaryWindow.setWindowTitle(_translate("PrimaryWindow", "OpihiExarata"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_astrometry), _translate("PrimaryWindow", "Astrometry"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_photometry), _translate("PrimaryWindow", "Photometry"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_propagate), _translate("PrimaryWindow", "Propagate"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_orbit), _translate("PrimaryWindow", "Orbit"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_ephemeris), _translate("PrimaryWindow", "Ephemeris"))
